server:
  port: 8080

spring:
  application:
    name: spring-auth-client

  security:
    oauth2:
      client:
        registration:
          myclient:
            client-id: myclient
            client-secret: secret # Plain text secret used at client side application but at auth server it should be hashed (BCrypt encoded) when password encoder is used
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          myclient:
            issuer-uri: http://localhost:9000
            user-name-attribute: sub

app:
  resource-server:
    base-url: http://localhost:8083
    get-endpoint: /products

logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      ss:
        ac: DEBUG
