server:
  port: 8084

spring:
  application:
    name: spring-resource-server-shopping

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      ss:
        rs:
          sh: DEBUG
